"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AutoresponderConfig(google.protobuf.message.Message):
    """
    Autoresponder module configuration.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOOTCOUNT_SINCE_ENABLED_FIELD_NUMBER: builtins.int
    RESPONSE_TEXT_FIELD_NUMBER: builtins.int
    PERMITTED_NODES_FIELD_NUMBER: builtins.int
    bootcount_since_enabled: builtins.int
    """
    How many times the device has booted since module enabled
    Prevents a frequently rebooting node from bypassing rate limits indefinitely
    Always applies to in-channel responses, optionally applies to DMs
    Doesn't count when this protection is not needed
    Int size 8
    """
    response_text: builtins.str
    """
    Predefined message, to be sent as an auto-response
    """
    @property
    def permitted_nodes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """
        Nodes to which we should respond
        """

    def __init__(
        self,
        *,
        bootcount_since_enabled: builtins.int = ...,
        response_text: builtins.str = ...,
        permitted_nodes: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bootcount_since_enabled", b"bootcount_since_enabled", "permitted_nodes", b"permitted_nodes", "response_text", b"response_text"]) -> None: ...

global___AutoresponderConfig = AutoresponderConfig
